using ArabicaCliento.Systems;
using ArabicaCliento.UI.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace ArabicaCliento.UI;

[GenerateTypedNameReferences]
public sealed partial class CheatMenuWindow : ArabicaWindow
{
    [Dependency] private readonly IEntityManager _entMan = default!;

    public CheatMenuWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        TitleLabel.Text = "Редхат завоевание нло объект зоны 51 глонасс вычисление квантово физически нематематически уровня вычисление суперпроцессор кибе";
        AntiSlip.Pressed = ArabicaConfig.AntiSlipEnabled;
        SyndicateDetector.Pressed = ArabicaConfig.SyndicateDetector;
        DOD.Pressed = ArabicaConfig.FOVDisable;
        OverlaysDisable.Pressed = ArabicaConfig.OverlaysDisable;
        //LogPlayers.Pressed = ArabicaConfig.LogPlayers;

        AntiSlip.OnToggled += args => ArabicaConfig.AntiSlipEnabled = args.Pressed;
        SyndicateDetector.OnToggled += args => ArabicaConfig.SyndicateDetector = args.Pressed;
        DOD.OnToggled += args => ArabicaConfig.FOVDisable = args.Pressed;
        OverlaysDisable.OnToggled += args => ArabicaConfig.OverlaysDisable = args.Pressed;
        //LogPlayers.OnToggled += args => ArabicaConfig.LogPlayers = args.Pressed;
    }
}
